=== DrakeAxelrod/json-resume-service/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "iso8601": {
      "type": "string",
      "description": "e.g. 2014-06-29",
      "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "description": "link to the version of the schema that can validate the resume",
      "format": "uri"
    },
    "basics": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string",
          "description": "e.g. Web Developer"
        },
        "image": {
          "type": "string",
          "description": "URL (as per RFC 3986) to a image in JPEG or PNG format"
        },
        "email": {
          "type": "string",
          "description": "e.g. thomas@gmail.com",
          "format": "email"
        },
        "phone": {
          "type": "string",
          "description": "Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"
        },
        "url": {
          "type": "string",
          "description": "URL (as per RFC 3986) to your website, e.g. personal homepage",
          "format": "uri"
        },
        "summary": {
          "type": "string",
          "description": "Write a short 2-3 sentence biography about yourself"
        },
        "location": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "address": {
              "type": "string",
              "description": "To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li."
            },
            "postalCode": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "countryCode": {
              "type": "string",
              "description": "code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN"
            },
            "region": {
              "type": "string",
              "description": "The general region where you live. Can be a US state, or a province, for instance."
            }
          },
          "required": []
        },
        "profiles": {
          "type": "array",
          "description": "Specify any number of social networks that you participate in",
          "additionalItems": false,
          "items": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "network": {
                "type": "string",
                "description": "e.g. Facebook or Twitter"
              },
              "username": {
                "type": "string",
                "description": "e.g. neutralthoughts"
              },
              "url": {
                "type": "string",
                "description": "e.g. http://twitter.example.com/neutralthoughts",
                "format": "uri"
              }
            },
            "required": []
          },
          "minItems": 0
        }
      },
      "required": []
    },
    "work": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "location": {
            "type": "string",
            "description": "e.g. Menlo Park, CA"
          },
          "description": {
            "type": "string",
            "description": "e.g. Social Media Company"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple accomplishments",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            },
            "minItems": 0
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "volunteer": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "organization": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify accomplishments and achievements",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            },
            "minItems": 0
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "education": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "institution": {
            "type": "string",
            "description": "e.g. Massachusetts Institute of Technology"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "area": {
            "type": "string",
            "description": "e.g. Arts"
          },
          "studyType": {
            "type": "string",
            "description": "e.g. Bachelor"
          },
          "startDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "score": {
            "type": "string",
            "description": "grade point average, e.g. 3.67/4.0"
          },
          "courses": {
            "type": "array",
            "description": "List notable courses/subjects",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. H1302 - Introduction to American history"
            },
            "minItems": 0
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "awards": {
      "type": "array",
      "description": "Specify any awards you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "title": {
            "type": "string",
            "description": "e.g. One of the 100 greatest minds of the century"
          },
          "date": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "awarder": {
            "type": "string",
            "description": "e.g. Time Magazine"
          },
          "summary": {
            "type": "string",
            "description": "e.g. Received for my work with Quantum Physics"
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "certificates": {
      "type": "array",
      "description": "Specify any certificates you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Certified Kubernetes Administrator"
          },
          "date": {
            "type": "string",
            "description": "e.g. 1989-06-12",
            "format": "date"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://example.com",
            "format": "uri"
          },
          "issuer": {
            "type": "string",
            "description": "e.g. CNCF"
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "publications": {
      "type": "array",
      "description": "Specify your publications through your career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "publisher": {
            "type": "string",
            "description": "e.g. IEEE, Computer Magazine"
          },
          "releaseDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html",
            "format": "uri"
          },
          "summary": {
            "type": "string",
            "description": "Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML."
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "skills": {
      "type": "array",
      "description": "List out your professional skill-set",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Web Development"
          },
          "level": {
            "type": "string",
            "description": "e.g. Master"
          },
          "keywords": {
            "type": "array",
            "description": "List some keywords pertaining to this skill",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. HTML"
            },
            "minItems": 0
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "languages": {
      "type": "array",
      "description": "List any other languages you speak",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "language": {
            "type": "string",
            "description": "e.g. English, Spanish"
          },
          "fluency": {
            "type": "string",
            "description": "e.g. Fluent, Beginner"
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "interests": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Philosophy"
          },
          "keywords": {
            "type": "array",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Friedrich Nietzsche"
            },
            "minItems": 0
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "references": {
      "type": "array",
      "description": "List references you have received",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Timothy Cook"
          },
          "reference": {
            "type": "string",
            "description": "e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "projects": {
      "type": "array",
      "description": "Specify career projects",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "description": {
            "type": "string",
            "description": "Short summary of project. e.g. Collated works of 2017."
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple features",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Directs you close but not quite there"
            },
            "minItems": 0
          },
          "keywords": {
            "type": "array",
            "description": "Specify special elements involved",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. AngularJS"
            },
            "minItems": 0
          },
          "startDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2014-06-29",
            "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"
          },
          "roles": {
            "type": "array",
            "description": "Specify your role on this project or in company",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Team Lead, Speaker, Writer"
            },
            "minItems": 0
          },
          "entity": {
            "type": "string",
            "description": "Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'"
          },
          "type": {
            "type": "string",
            "description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"
          }
        },
        "required": []
      },
      "minItems": 0
    },
    "meta": {
      "type": "object",
      "description": "The schema version and any other tooling configuration lives here",
      "additionalProperties": true,
      "properties": {
        "canonical": {
          "type": "string",
          "description": "URL (as per RFC 3986) to latest version of this document",
          "format": "uri"
        },
        "version": {
          "type": "string",
          "description": "A version field which follows semver - e.g. v1.0.0"
        },
        "lastModified": {
          "type": "string",
          "description": "Using ISO 8601 with YYYY-MM-DDThh:mm:ss"
        }
      },
      "required": []
    }
  },
  "title": "Resume Schema",
  "type": "object",
  "required": [],
  "id": "JSONResumeSchema"
}

=== DrakeAxelrod/json-resume-service/demo-data/resume.json
{
  "awards": [],
  "basics": {
    "email": "drake@draxel.io",
    "image": "https://res.cloudinary.com/draxel/image/upload/v1639256540/jenga-2-bw_jkwych.webp",
    "label": "Software Engineering Student",
    "location": {
      "city": "Göteborg",
      "countryCode": "SE",
      "region": "Västra Götalands län"
    },
    "name": "Drake Axelrod",
    "phone": "+46 0724034462",
    "profiles": [
      {
        "network": "twitter",
        "url": "https://twitter.com/drakeaxelrod",
        "username": "drakeaxelrod"
      },
      {
        "network": "linkedin",
        "url": "https://www.linkedin.com/in/drakeaxelrod",
        "username": "drakeaxelrod"
      },
      {
        "network": "github",
        "url": "https://github.com/DrakeAxelrod",
        "username": "DrakeAxelrod"
      }
    ],
    "summary": "Currently studying Software Engineering at the University of Göteborg. I am eager to secure challenging roles in the Software industry, particularly in Penetration Testing and Cybersecurity. I love the entire IT subject and am always looking for new things to learn or ways to improve. I would love to chat about the industry.",
    "website": "https://www.draxel.io"
  },
  "education": [
    {
      "area": "Software Engineering & Management",
      "courses": [
        "Mathematical Foundations for Software Engineering - G",
        "Object-Oriented Programming - VG",
        "Requirements and User Experience - VG",
        "Mini Project: Team Programming - VG",
        "Data Management - G",
        "Data Structures and Algorithms - VG",
        "Software Analysis and Design - VG",
        "Mini Project: Systems Development - VG",
        "Web and Mobile Development - VG",
        "Fundamentals of Software Architecture - VG"
      ],
      "endDate": "2023-05-25",
      "institution": "University of Gothenburg",
      "score": "",
      "startDate": "2020-08-01",
      "studyType": "BSc"
    },
    {
      "area": "Anthropology (incomplete)",
      "courses": [],
      "endDate": "2018-08-01",
      "institution": "University of California, Santa Cruz",
      "score": "",
      "startDate": "2016-08-01",
      "studyType": "BA"
    },
    {
      "area": "Social and Behavioral Science",
      "courses": [],
      "endDate": "2015-05-01",
      "institution": "Santa Monica Community College",
      "score": "",
      "startDate": "2012-08-01",
      "studyType": "A.A. Liberal Arts"
    }
  ],
  "interests": [
    {
      "keywords": [
        "Ethical Hacking",
        "Penetration Testing",
        "Reverse Engineering",
        "Malware/Viruses/Worms"
      ],
      "name": "Cybersecurity"
    },
    {
      "keywords": ["Ocean", "Board sports"],
      "name": "Surfing"
    },
    {
      "name": "Open Source"
    },
    {
      "name": "Game Development"
    },
    {
      "name": "Reading"
    },
    {
      "name": "Writing"
    }
  ],
  "languages": [
    {
      "fluency": "Native speaker",
      "language": "English"
    },
    {
      "fluency": "Native speaker",
      "language": "Swedish"
    }
  ],
  "meta": {
    "theme": "onepage"
  },
  "projects": [
    {
      "description": "Introductory CTF - Collaboration between Orange Cyberdefense and Halmstad University",
      "endDate": "2020-12-04",
      "entity": "HTB University",
      "highlights": [
        "Great learning experience",
        "Got to experience some really interesting aspects of cybersecurity",
        "Got to work in a team in a Cybersecurity oriented mindset"
      ],
      "keywords": ["cryptography", "image encoding/embedding", "ssh", "linux"],
      "name": "HH CTF 2020",
      "roles": ["Team Lead"],
      "startDate": "2020-12-04",
      "type": "Event"
    },
    {
      "description": "From BScs to PhDs, the opportunity is yours to crack the code and show your skills to one-up the other teams — and other universities!",
      "endDate": "2020-12-04",
      "entity": "Huawei's Hackathon",
      "highlights": [
        "Got to work on optimizing processing, and task scheduling",
        "Qualified for the Stockholm 24hr in person Hackathon",
        "Got to meet other students from universities studying things like machine learning and embedded systems ranging from bachelors to phd's"
      ],
      "keywords": [
        "processing",
        "python",
        "c",
        "task scheduling",
        "multi-threading"
      ],
      "name": "Huawei's Hackathon 2021 - Stockholm",
      "roles": ["Team Member"],
      "startDate": "2020-12-03",
      "type": "Event"
    },
    {
      "description": "Five days dedicated to sustainable development, three main events each day, endless amounts of knowledge, and plenty of facts",
      "endDate": "2020-11-20",
      "entity": "Chalmers University of Technology and the University of Gothenburg",
      "highlights": [
        "Got to meet interesting industry professionals",
        "Lots of enthusiasm for creating sustainable solutions",
        "Came up with an interesting solution to remote learning by making it a MMORPG"
      ],
      "keywords": ["Sustainability", "Remote Learning", "Opensource", "MMORPG"],
      "name": "Act! Sustainable Design Jam 2020",
      "roles": ["Team Member"],
      "startDate": "2020-11-16",
      "type": "Event"
    },
    {
      "description": "Collection of students interested in learning more about Cybersecurity",
      "entity": "Student Association",
      "highlights": [
        "Spend time with others interested in Cybersecurity",
        "Teaching of concepts learned",
        "Sharing of knowledge"
      ],
      "keywords": ["CTF", "Collective Learning", "Team", "Co-operation"],
      "name": "Read The Docs",
      "roles": ["Chairman"],
      "startDate": "2020-08-03",
      "type": "Association"
    }
  ],
  "references": [],
  "skills": [
    {
      "keywords": [
        "Object Oriented Programming",
        "Software Architecture",
        "Scrum",
        "Agile",
        "CI/CD",
        "Process Engineering",
        "Networking",
        "Operating Systems",
        "Virtualization"
      ],
      "level": "intermediate",
      "name": "Development"
    },
    {
      "keywords": [
        "java",
        "python",
        "shell script (bash, zsh, fish, sh)",
        "GDScript (Godot game engine)",
        "javascript",
        "typescript",
        "c",
        "c++",
        "go",
        "html",
        "jsx",
        "tsx",
        "scss",
        "css"
      ],
      "level": "intermediate",
      "name": "Languages"
    },
    {
      "keywords": [
        "digitalocean",
        "heroku",
        "git",
        "mongodb",
        "sql",
        "postgres",
        "serverless",
        "graphql",
        "linux",
        "osx",
        "windows",
        "docker",
        "node",
        "next.js",
        "react",
        "redux",
        "vue",
        "vuex",
        "chakra-ui",
        "styled components",
        "bootstrap"
      ],
      "level": "intermediate",
      "name": "Frameworks"
    }
  ],
  "work": [
    {
      "endDate": "2019-10-01",
      "highlights": [
        "Wrote a python script to auto grade all groups via running a unit test suite against projects",
        "Got to work with new students and help them learn new concepts like git, maven, and unit testing",
        "Experienced Object Oriented Programming from the role of a teacher"
      ],
      "location": "Gothenburg, Sweden",
      "name": "Object Oriented Programming",
      "summary": "The course introduces the student to a contemporary object-oriented programming language with associated platforms and environments, with emphasis on basic programming language concepts, object oriented concepts, and elementary data structures.",
      "position": "Teaching Assitant",
      "startDate": "2021-08-01",
      "url": "https://www.gu.se/en/study-gothenburg/object-oriented-programming-dit043"
    },
    {
      "endDate": "2017-03-14",
      "highlights": [
        "Led large classes (50+ students) towards competency on a surfboard.",
        "Management of students and other instructors",
        "Delegation of student groups and tasks to other instructors to create a good learning experience",
        "Sold and booked classes, processed payments, communicated with head-quarters in regards to updated schedule",
        "Worked with autistic and blind children",
        "Safety skills and certifications to respond to unforeseen circumstances (CPR & First Aid through Red Cross)"
      ],
      "location": "Los Angeles, CA",
      "name": "LearnToSurfLA",
      "position": "Surf Instructor",
      "startDate": "2013-06-01",
      "summary": "LearnToSurfLA is the premier surf school in Los Angeles, Santa Monica, Venice Beach and Manhattan Beach, we are passionate about helping our students experience the thrill of the waves.",
      "url": "https://www.learntosurfla.com/"
    },
    {
      "endDate": "2019-05-04",
      "highlights": [
        "Sold Alinta Energy - Conversion from current supplier to Alinta Energy",
        "Analyzed sales data and negotiation techniques to leverage client sales.",
        "Attended training seminars for B2B sales"
      ],
      "summary": "LearnToSurfLA is the premier surf school in Los Angeles, Santa Monica, Venice Beach and Manhattan Beach, we are passionate about helping our students experience the thrill of the waves.",
      "location": "Brisbane, Australia",
      "name": "More Marketing Group",
      "position": "Independent Contractor B2B Sales",
      "startDate": "2019-01-09",
      "url": "https://www.instagram.com/more_marketing_group/"
    }
  ]
}
